const data = {
    products: [
        {
            _id: '1',
            name: 'Purple color saree',
            category: 'saree',
            image: '../images/img7.png',
            price: '2,500.00',
            countInStock: 10,
            rating: 4.0,
            numReviews: 12,
            description: "high quality product",
        },
        {
            _id: '2',
            name: 'Baby pink Chiffon Saree',
            category: 'saree',
            image: '../images/img4.jpg',
            price: '1,000.00',
            countInStock: 9,
            rating: 4.5,
            numReviews: 25,
            description: "high quality product",
        },
        {
            _id: '3',
            name: 'Women Handloom Cotton Silk Saree',
            category: 'saree',
            image: '../images/img12.jpeg',
            price: '1,500.00',
            countInStock: 20,
            rating: 4.0,
            numReviews: 15,
            description: "high quality product",
        },
        {
            _id: '4',
            name: 'Banarasi Cotton Silk Saree',
            category: 'saree',
            image: '../images/img3.jpg',
            price: '2,200.00',
            countInStock: 18,
            rating: 4.0,
            numReviews: 19,
            description: "high quality product",
        },
        {
            _id: '5',
            name: 'Soft Cotton and Silk Saree',
            category: 'saree',
            image: '../images/img.png',
            price: '1,150.00',
            countInStock: 40,
            rating: 4.0,
            numReviews: 80,
            description: "high quality product",
        },
        {
            _id: '6',
            name: 'Ishin Womens Pure Georgette Saree',
            category: 'saree',
            image: '../images/imge1.jpg',
            price: '2,200.00',
            countInStock: 50,
            rating: 4.5,
            numReviews: 32,
            description: "high quality product",
        },
        {
            _id: '7',
            name: 'Yevala paithani women saree',
            category: 'saree',
            image: '../images/imge2.jpg',
            price: '3,500.00',
            countInStock: 60,
            rating: 4.0,
            numReviews: 30,
            description: "high quality product",
        },
        {
            _id: '8',
            name: 'Womens Chiffon Saree',
            category: 'saree',
            image: '../images/img8.png',
            price: '1,700.00',
            countInStock: 30,
            rating: 4.0,
            numReviews: 80,
            description: "high quality product",
        },
        {
            _id: '9',
            name: 'Banarasi Cotton Silk Saree',
            category: 'saree',
            image: '../images/img9.png',
            price: '1,150.00',
            countInStock: 24,
            rating: 4.5,
            numReviews: 45,
            description: "high quality product",
        },
        {
            _id: '10',
            name: 'Womens Khadi Silk Saree',
            category: 'saree',
            image: '../images/img11.jpg',
            price: '3,200.00',
            countInStock: 12,
            rating: 5.0,
            numReviews: 20,
            description: "high quality product",
        },
        {
            _id: '11',
            name: 'Chanderi Silk Saree',
            category: 'saree',
            image: '../images/img9.jpg',
            price: '1,600.00',
            countInStock: 17,
            rating: 5.0,
            numReviews: 70,
            description: "high quality product",
        },
        {
            _id: '12',
            name: 'Silk blue saree',
            category: 'saree',
            image: '../images/img10.jpg',
            price: '1,800.00',
            countInStock: 0,
            rating: 5.0,
            numReviews: 11,
            description: "high quality product",
        },

    ],
};
module.exports = data;